[package]
authors = ["Nick Massey <nickmass@nickmass.com>"]
name = "web-tetris"
version = "0.1.0"

[dependencies]
random = "0.12.2"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_json = "1.0.8"
stdweb = "0.4.0"
